### ISSUE TITLE
Error running the example notebook from biohackathon MENA 2023

### ISSUE THREAD

**Issue by vemonet** [bio-ontology-research-group/mowl#42]
Trying to run the notebook available here: https://drive.google.com/drive/folders/1JHbaV__9f_zVx-lIvp82b2mvc6AjaseJ

Everything works until this codeblock:

```python
from gensim.models.word2vec import LineSentence
from gensim.models import Word2Vec

walk_corpus_file = walker.outfile
sentences = LineSentence(walk_corpus_file)

w2v_model = Word2Vec(sentences, size = 20)
```

Which gives this error: 

```
TypeError                                 Traceback (most recent call last)
Cell In [27], line 7
      4 walk_corpus_file = walker.outfile
      5 sentences = LineSentence(walk_corpus_file)
----> 7 w2v_model = Word2Vec(sentences, size = 20)

TypeError: __init__() got an unexpected keyword argument 'size'
```

It seems like the issue comes from the version of Gensim installed by mOWL. There are currently no specification for the gensim version, it might be necessary to add one: https://github.com/bio-ontology-research-group/mowl/blob/main/environment.yml#L8

The versions installed for me are:
- python 3.9.15
- gensim 4.3.0

**Comment by vemonet** [comment]
I noticed that the README mention that mOWL only works on python 3.8, which is quite restraining 

It would be nice to provide a `Dockerfile` to "easily" use mOWL without needing to do many changes

And specify in mOWL package metadata that `python >=3.8,<3.9` is required

**Comment by ferzcam** [comment]
Dear @vemonet. Sorry for the very late response. We had some dependency issues, particularly in Colab (where the notebook was run in the tutorial). This would be a better source of information [Embedding with Random Walks](https://mowl.readthedocs.io/en/latest/graphs/random_walks.html).

Also, thank you for the suggestion about Python version. We will work on a more transparent way of indicating the dependencies.
