### ISSUE TITLE
Check Python 3.14 compatibility and add it to the supported matrix

### ISSUE THREAD

**Issue by ferzcam** [bio-ontology-research-group/mowl#162]
## Summary

mOWL currently supports Python 3.10–3.13. `setup.py` caps `python_requires=">=3.10, <3.14"`, with a comment attributing the cap to JPype1 compatibility. Python 3.14 is out (October 2025) and looks supportable now — initial findings below.

## Initial findings (2026-09-10)

- **JPype1 (the stated blocker) no longer blocks.** The pinned `JPype1==1.7.1` ships cp314 wheels (manylinux, macOS, Windows) and conda-forge has a `py314` build of 1.7.1. (JVM integration not yet verified end-to-end — see checklist.)
- **`scipy<1.16.0` is a real blocker.** Only scipy >= 1.16.1 publishes cp314 wheels, so the current pin cannot be installed on 3.14 at all. History check: the cap is legacy — it has only ever been bumped mechanically by Dependabot (`<1.15.0` → `<1.16.0`, #c799b64), it is not a functional guard. mOWL only uses `scipy.stats.rankdata`, so lifting the cap is low-risk.
- **`gensim>=4.3.0` is currently a hard blocker.** No gensim release up to and including 4.4.0 publishes cp314 wheels, and the sdist no longer compiles on 3.14 (C extension uses `PyLongObject.ob_digit`, removed from CPython). gensim is only imported by the graph/syntactic models (`graph_random_walk`, `syntactic`, `inference/cosine`, `visualization/base`), not the EL core. **We must wait for a gensim release with cp314 wheels before 3.14 support can land** — re-check on every gensim release.
- Remaining pins to verify on 3.14: `pykeen==1.11.1`, `class-resolver==0.7.1`, torch (conda-forge), and the owlapi jars over JPype in the EL pipeline.

## Checklist

- [x] Raise the `scipy<1.16.0` cap to `<1.18.0` (1.16.x + 1.17.x admitted; 1.17.1 verified with the full fast suite; 3.10–3.13 unaffected since 3.10 tops out at 1.15.x anyway) → separate small PR
- [ ] Wait for a gensim release with cp314 wheels (blocks everything; re-check periodically)
- [ ] Build a python 3.14 env (mirror of `envs/environment_3_XX.yml`) and run the full `pytest -m "not slow"` suite
- [ ] Verify JPype1 1.7.1 + the owlapi jars actually work on 3.14 (JVM start, ontology load, EL normalisation) — a cp314 wheel existing is not the same as the integration working
- [ ] Check the remaining pins (`pykeen==1.11.1`, `class-resolver==0.7.1`, torch) on 3.14
- [ ] Add `envs/environment_3_14.yml` and a CI matrix entry in `.github/workflows/unittests.yml`
- [ ] Bump `python_requires` and add the 3.14 classifier in `setup.py`
- [ ] Decide whether to drop 3.10 in the same pass (Python 3.10 reaches EOL in October 2026)

## Note for maintainers

Dependabot will never flag a new Python version: it only tracks package dependencies in manifests, and the interpreter version (the `python_requires` cap, the conda env files, the CI matrix) is configuration, not a dependency. The scipy cap that blocked 3.14 was in fact maintained *by* Dependabot, which raised it mechanically without anyone noticing it would later block 3.14. A periodic (monthly) manual or workflow check for new CPython releases is the only alert mechanism.
